version: "3"

services:
  chgo:
    image: daxua/chgo:0.0.4
    # build: .
    restart: always
    container_name: chgo
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - PORT=9000
      - PG_USER=postgres
      - PG_PASSWORD=c9BqhGZM5v7EPTs7
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DB=chstore
    ports:
      - 9000:9000

  postgres:
    image: postgres:10
    restart: always
    container_name: postgres
    hostname: postgres
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: c9BqhGZM5v7EPTs7
      POSTGRES_DB: chstore
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
