version: "3"

services:
  postgres:
    image: postgres:10
    restart: always
    container_name: postgres
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: c9BqhGZM5v7EPTs7
      POSTGRES_DB: chstore
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
