version: "3"

services:
  postgres:
    image: postgres:10.1-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - POSTGRES_PASSWORD=c9BqhGZM5v7EPTs7
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tasks
    ports:
      - 5432:5432
